### ISSUE TITLE
"Getting Started" on the website not working on iPhone

### ISSUE THREAD

**Issue by arjuan** [openscore/openscore.github.io#1]
Pressing the "Start Now" link rolls the screen down to the "Getting Started" section then neither the "Download and use..." nor the "Embed score..." seems to be functioning links. If this is on purpose then we should consider a better content on the website for mobile (where for example download isn't relevant)

**Comment by dorsha** [comment]
We don't want users to download the CLI from their iPhone

**Comment by arjuan** [comment]
That's understood and wasn't my intent anyway. but still need a reasonable user experience for mobile users.

**Comment by orius123** [comment]
so what do we want to give the mobile guys?

**Comment by orius123** [comment]
And we will enable download to a phone??

**Comment by dorsha** [comment]
No, it should be disabled and we can mention the npm install....

**Comment by arjuan** [comment]
no download to mobile
