### ISSUE TITLE
how do we want to document content actions

### ISSUE THREAD

**Issue by orius123** [openscore/openscore.github.io#10]
we have java docs of the content actions, we can reformat it to markdown files, but I'm not sure where/how should we show it in the site,
currently we have for the existing action but it is supposed to grow as we develop new actions.
I was thinking of a new page/section that will have a table of all actions and when clicking  on a row it will expand with the data.

@dorsha @meshipeer @oritstone @SamMarkowitz WDYT?
adding @ioanvranauhp

**Comment by meshipeer** [comment]
hi,
i think its great to have JavaDocs, we should generate it and put it on a separate link.
i think we should have high level content docs, but i think information about operations, for example, can be even more important. and i hope we have contribution from outside, so maybe we want to have wiki for slang-content repo and we'll add deocs for that too.

WDYT?

**Comment by meirwah** [comment]
:+1:

**Comment by SamMarkowitz** [comment]
Also agree. Do you want me to look them over before publishing?

**Comment by oritstone** [comment]
I agree with Meshi. We should have JavaDocs for he Java actions somewhere, and it can be easily generated.
Regarding the slang files, I think it will not be maintainable to update an external wiki manually for each change in the comments. Maybe we should think of some way to better formulate the structure of the comments, and have some automatic way to generate the documentation from the slang files.
