### ISSUE TITLE
slang-embedded not working...

### ISSUE THREAD

**Issue by meirwah** [openscore/openscore.github.io#12]
missing from Maven central:
io.openscore.lang:score-language:pom:0.1.5

I created a new project to test it + Travis job on it:
https://travis-ci.org/meirwah/test-slang-embedded
https://github.com/meirwah/test-slang-embedded

Also need to update the website on it (correct versions):
<dependency>
            <groupId>io.openscore</groupId>
            <artifactId>score-all</artifactId>
            <version>0.1.251</version>
        </dependency>

        <dependency>
            <groupId>io.openscore.lang</groupId>
            <artifactId>score-lang-api</artifactId>
            <version>0.1.5</version>
        </dependency>

@hararzafrir @orius123 can you upload to M.C.?

**Comment by dorsha** [comment]
Done (website changes).

**Comment by meirwah** [comment]
FIXED .. need version <version>0.1.8</version> for slang
