### ISSUE TITLE
web UI defect

### ISSUE THREAD

**Issue by maayannoy** [openscore/openscore.github.io#30]
In the main page of score website, under "Download CLI" the text look bad, see link:
http://i.imgur.com/3A3OcyG.png
we enter the site via the old url (http://scoreslang.herokuapp.com/#/)

**Comment by dorsha** [comment]
Known issue. Occurs just when going back from docs to the home page while the "Download CLI" was opened.

**Comment by orius123** [comment]
fixed when using custom directive.
