### ISSUE TITLE
error in spring configuration in 'Embed score library in your application'

### ISSUE THREAD

**Issue by avifro** [openscore/openscore.github.io#32]
please fix 
'http://www.openscore.org/schema/score/score.xsd' 
to
'http://www.openscore.org/schema/score.xsd'

**Comment by meirwah** [comment]
if we fix this.. i think changes will be needed to OO too

**Comment by meirwah** [comment]
or is it just in the website?

**Comment by avifro** [comment]
I just encountered in it in the website

**Comment by orius123** [comment]
will do
