### ISSUE TITLE
fix examples in docs + provide example repo

### ISSUE THREAD

**Issue by orius123** [openscore/openscore.github.io#36]
we need to fix few places where we have problems in the docs examples.
and in general we need to create an example repo, and store all of the examples in there, after we **tested** that everything in there is running

**Comment by SamMarkowitz** [comment]
Which examples don't run?

Instead of another repo can we add a folder to this one where the full example code will reside?

**Comment by orius123** [comment]
how about making a directory with the examples like @SamMarkowitz suggested, and make all of the examples in the site + docs downloadable. @dorsha @SamMarkowitz  WDYT?

**Comment by SamMarkowitz** [comment]
Agree. Especially since the indentation doesn't always copy over the same way, depending on the tools you're using. And the indentation is quite important.

**Comment by SamMarkowitz** [comment]
@orius123 What did we decide? That we'll add a folder within the site? Where should I put it?

**Comment by orius123** [comment]
I would put it under a new directory. `app/slang-content`

**Comment by SamMarkowitz** [comment]
Fixed via b4864176bc4c2a68712fc97634b99ac39f557bb3
