### ISSUE TITLE
make docs examples from usable cases

### ISSUE THREAD

**Issue by orius123** [openscore/openscore.github.io#37]
example 3 for instance is not usable in any way..

**Comment by SamMarkowitz** [comment]
The idea was to keep it simple and direct to the point (using subflows for that example) without introducing too much code (example 3 uses example 1 as it's subflow) at the expense of the usability. The slang-content repository will be filled with usable stuff. 

Definitely open to other ideas for the examples. Let me know you're ideas and I'll write them up if they don't already exist.
