### ISSUE TITLE
Fix SLANG best practices section in docs

### ISSUE THREAD

**Issue by oritstone** [openscore/openscore.github.io#47]
- Fix the first bullet about the namespace. The namespace is not identical, but matches the suffix of the file path. It's best to give an example from our content, with a full path of a file, and its namespace
- Namespace should be comprised only of lower-case alphanumeric characters (a-z, 0-9), underscore (_), hyphen (-) or dot(.)
- Each file has one flow, one operation (cannot be sys props)
- Remove bullet: System variables reside in separate folders - not relevant anymore
- Regarding the note about the SLANG compiler, it is worthwhile to state that we have the slang content verifier tool that verifies validity.

**Comment by SamMarkowitz** [comment]
@oritstone: Please review. I left the last one out. I think I'll probably add a section about the verifier. Once I do that, I'll add something here too.

**Comment by SamMarkowitz** [comment]
Put the last one in and added the verifier section.
