### ISSUE TITLE
Add privacy policy statement on website

### ISSUE THREAD

**Issue by gfachler** [openscore/openscore.github.io#6]
@dorsha @meshipeer 
Because we are using Google Analytics, we were told by Legal to we need to add the following privacy policy at the footer of our website:
This website incorporates HP's Privacy Policy (with a link to  http://www8.hp.com/us/en/privacy/privacy.html)

**Comment by dorsha** [comment]
Do we need to need to use the HP link?

**Comment by gfachler** [comment]
I think we do need the link. That is what was suggested by Legal. I assume people need to be able to see that actual policy

**Comment by orius123** [comment]
Ok. So we will add at the footer a link "Privacy policy" to the link you gave.

**Comment by gfachler** [comment]
We need to put in the full sentence "This website incorporates HP's Privacy Policy" with the link inside

**Comment by orius123** [comment]
added.
@dorsha do you think we need to make less space between those 3 lines?
feel free to close if not.

**Comment by SamMarkowitz** [comment]
Only one of the lines has a period at the end. I think all three should.

**Comment by dorsha** [comment]
All lines should be with period at the end.
I also think that the copyright and the policy should be on the same line.
